# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aicrawler < Formula
  desc "Daily AI news briefings"
  homepage "https://github.com/TobiSchelling/AICrawler"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.3/AICrawler_1.0.3_darwin_amd64.tar.gz"
      sha256 "58235201b24d271533ba4aa621e1411b64bfefed4f121a828b8e04629bfedcc2"

      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.3/AICrawler_1.0.3_darwin_arm64.tar.gz"
      sha256 "8b6f4133cada5d98496035b97749715b9f3f1419ce76fb22220e2c66d59e415b"

      def install
        bin.install "aicrawler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.3/AICrawler_1.0.3_linux_amd64.tar.gz"
      sha256 "9961ab1eebc3cbba2a17a75de9818b91934411200d1b431c2dd7a468b3878be5"
      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.3/AICrawler_1.0.3_linux_arm64.tar.gz"
      sha256 "40d9f6cdae983d0a10897c291a60f0d327de26545cc70cdb8a4009f237de461e"
      def install
        bin.install "aicrawler"
      end
    end
  end

  test do
    assert_match "Daily AI news briefings", shell_output("#{bin}/aicrawler --help")
  end
end
