# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aicrawler < Formula
  desc "Daily AI news briefings"
  homepage "https://github.com/TobiSchelling/AICrawler"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.5/AICrawler_1.0.5_darwin_amd64.tar.gz"
      sha256 "d06553a779e0ce0ef4145ffda34897dd1a362b4b8b24dece2327c86bfc9bd946"

      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.5/AICrawler_1.0.5_darwin_arm64.tar.gz"
      sha256 "f8ce5cbd032af49fe984017b76fb2060e884361b0b8c9647b6bdb266711c11fb"

      def install
        bin.install "aicrawler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.5/AICrawler_1.0.5_linux_amd64.tar.gz"
      sha256 "292ed840c44045bcf01e88d9cd07ee94b87255c4df341995af4df6bf7cc0c2ae"
      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.5/AICrawler_1.0.5_linux_arm64.tar.gz"
      sha256 "6f31a5d7f7d59dfaea3acaa25547fc94992f2e65fafb52aa1b6288671252f769"
      def install
        bin.install "aicrawler"
      end
    end
  end

  test do
    assert_match "Daily AI news briefings", shell_output("#{bin}/aicrawler --help")
  end
end
