# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aicrawler < Formula
  desc "Daily AI news briefings"
  homepage "https://github.com/TobiSchelling/AICrawler"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.1/AICrawler_1.0.1_darwin_amd64.tar.gz"
      sha256 "cfbbf7e56c88d3fb5be6acb94a0ed31cb73259b4edbc7881f96441b45c14595d"

      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.1/AICrawler_1.0.1_darwin_arm64.tar.gz"
      sha256 "badf241380318546e39e5f73acd3559942fc76fe999d63e6ffd28e47f70add09"

      def install
        bin.install "aicrawler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.1/AICrawler_1.0.1_linux_amd64.tar.gz"
      sha256 "d384e8139f1681c321e177707bfe77aac9a761df539676ae395f06d4bfdc5c7b"
      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.1/AICrawler_1.0.1_linux_arm64.tar.gz"
      sha256 "3d46d1020e00cfd31badcf661e62813328b5ebfa3c98adcdb0e30bfbcd45bc0b"
      def install
        bin.install "aicrawler"
      end
    end
  end

  test do
    assert_match "Daily AI news briefings", shell_output("#{bin}/aicrawler --help")
  end
end
