# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aicrawler < Formula
  desc "Daily AI news briefings"
  homepage "https://github.com/TobiSchelling/AICrawler"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.4/AICrawler_1.0.4_darwin_amd64.tar.gz"
      sha256 "e4e9c4c805d6c307e5297860aeef96aa22134c9f9e0e9e93f91d57114426aa9f"

      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.4/AICrawler_1.0.4_darwin_arm64.tar.gz"
      sha256 "91aa96c0f41a8f59ab04daa6d34da43bf62f425cc4203b44680090cd021b6cf0"

      def install
        bin.install "aicrawler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.4/AICrawler_1.0.4_linux_amd64.tar.gz"
      sha256 "9ba4e8a1a77309ed81e80855e27fd6a9dda45830d11b8255b0a2773e2f7040fe"
      def install
        bin.install "aicrawler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TobiSchelling/AICrawler/releases/download/v1.0.4/AICrawler_1.0.4_linux_arm64.tar.gz"
      sha256 "b3b99be8959f1a549c9a10641e8e8cfa3efc2c95c30e3e3bbff8cf1fb6c657a9"
      def install
        bin.install "aicrawler"
      end
    end
  end

  test do
    assert_match "Daily AI news briefings", shell_output("#{bin}/aicrawler --help")
  end
end
